#!/bin/bash
#SBATCH --job-name=espace
#SBATCH --output=/home/aideb/stable-baselines3/base_job_output_gpu/Ant-v5/ppo_rank_fqe_out.txt
#SBATCH --error=/home/aideb/stable-baselines3/base_job_output_gpu/Ant-v5/ppo_rank_fqe_err.txt
#SBATCH --time=7-00:00
#SBATCH --mem=5000
#SBATCH --gres=gpu:1

# Test CUDA compiler (not needed by deep learning people, we just use the python libraries)
# /cm/shared/apps/cuda11.1/toolkit/11.1.1/bin/nvcc -o saxpy /home/aideb/cuda_c_code/saxpy.cu && ./saxpy

# Test nvidia-smi
nvidia-smi

# Test Python conda environment
source activate openv
/home/aideb/miniconda3/envs/openv/bin/python3 -u /home/aideb/stable-baselines3/main_gpu.py